apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
  labels:
    app: {{ .Values.app }}
spec:
  selector:
    app: {{ .Values.app }}
  ports:
    - port: {{ .Values.args.port }}
      name: http